{"ast":null,"code":"var _jsxFileName = \"C:\\\\E-Lfront\\\\PGDAC-Final-E-Learning-Frontend\\\\my-app\\\\src\\\\Pages\\\\ChapterContent\\\\Exceptionhandling.js\";\nimport React from 'react';\nimport Carousel from 'react-bootstrap/Carousel';\nimport ReactPlayer from 'react-player';\nimport './index.css';\nimport ContentNavi from '../../Components/Navbar/ContentNavi';\nimport { jsxDEV as _jsxDEV } from \"react/jsx-dev-runtime\";\n\nconst Exceptionhandling = () => {\n  return /*#__PURE__*/_jsxDEV(\"div\", {\n    className: \"Content\",\n    children: [/*#__PURE__*/_jsxDEV(ContentNavi, {}, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 11,\n      columnNumber: 9\n    }, this), /*#__PURE__*/_jsxDEV(\"h1\", {\n      children: \"Exceptions in Java\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 12,\n      columnNumber: 9\n    }, this), /*#__PURE__*/_jsxDEV(\"br\", {}, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 14,\n      columnNumber: 9\n    }, this), \" \", /*#__PURE__*/_jsxDEV(\"br\", {}, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 14,\n      columnNumber: 15\n    }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n      children: \"Exception Handling in Java is one of the effective means to handle the runtime errors so that the regular flow of the application can be preserved. Java Exception Handling is a mechanism to handle runtime errors such as ClassNotFoundException, IOException, SQLException, RemoteException, etc.\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 15,\n      columnNumber: 9\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"What is an Exception?\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 17,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n      children: \"An exception is an unwanted or unexpected event, which occurs during the execution of a program i.e at run time, that disrupts the normal flow of the program\\u2019s instructions. Exceptions can be caught and handled by the program. When an exception occurs within a method, it creates an object. This object is called the exception object. It contains information about the exception such as the name and description of the exception and the state of the program when the exception occurred.\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 18,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"An exception can occur for many reasons. Some of them are:\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 21,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"ul\", {\n      children: [/*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Invalid user input\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 23,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Device failure\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 24,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Loss of network connection\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 25,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Physical limitations (out of disk memory)\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 26,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Code errors\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 27,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Opening an unavailable file\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 28,\n        columnNumber: 5\n      }, this)]\n    }, void 0, true, {\n      fileName: _jsxFileName,\n      lineNumber: 22,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"What is an Error? \"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 31,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n      children: \"Errors represent irrecoverable conditions such as Java virtual machine (JVM) running out of memory, memory leaks, stack overflow errors, library incompatibility, infinite recursion, etc. Errors are usually beyond the control of the programmer and we should not try to handle errors.\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 32,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"Error vs Exception\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 36,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"ul\", {\n      children: [/*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Error: An Error indicates a serious problem that a reasonable application should not try to catch.\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 38,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Exception: Exception indicates conditions that a reasonable application might try to catch.\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 39,\n        columnNumber: 5\n      }, this)]\n    }, void 0, true, {\n      fileName: _jsxFileName,\n      lineNumber: 37,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"Exception Hierarchy\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 43,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n      children: \"All exception and errors types are subclasses of class Throwable, which is the base class of the hierarchy. One branch is headed by Exception. This class is used for exceptional conditions that user programs should catch. NullPointerException is an example of such an exception. Another branch, Error is used by the Java run-time system(JVM) to indicate errors having to do with the run-time environment itself(JRE). StackOverflowError is an example of such an error.\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 44,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(Carousel, {\n      children: /*#__PURE__*/_jsxDEV(Carousel.Item, {\n        interval: 1000,\n        children: [/*#__PURE__*/_jsxDEV(Carousel.Caption, {}, void 0, false, {\n          fileName: _jsxFileName,\n          lineNumber: 47,\n          columnNumber: 17\n        }, this), /*#__PURE__*/_jsxDEV(\"img\", {\n          src: require('https://media.geeksforgeeks.org/wp-content/uploads/Exception-in-java1.png'),\n          className: \"img\"\n        }, void 0, false, {\n          fileName: _jsxFileName,\n          lineNumber: 51,\n          columnNumber: 21\n        }, this)]\n      }, void 0, true, {\n        fileName: _jsxFileName,\n        lineNumber: 46,\n        columnNumber: 17\n      }, this)\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 45,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"Types of Exceptions\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 56,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n      children: \"Java defines several types of exceptions that relate to its various class libraries. Java also allows users to define their own exceptions.\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 57,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(Carousel, {\n      children: /*#__PURE__*/_jsxDEV(Carousel.Item, {\n        interval: 1000,\n        children: [/*#__PURE__*/_jsxDEV(Carousel.Caption, {}, void 0, false, {\n          fileName: _jsxFileName,\n          lineNumber: 60,\n          columnNumber: 17\n        }, this), /*#__PURE__*/_jsxDEV(\"img\", {\n          src: require('https://media.geeksforgeeks.org/wp-content/uploads/20220120111809/Group21-660x330.jpg'),\n          className: \"img\"\n        }, void 0, false, {\n          fileName: _jsxFileName,\n          lineNumber: 64,\n          columnNumber: 21\n        }, this)]\n      }, void 0, true, {\n        fileName: _jsxFileName,\n        lineNumber: 59,\n        columnNumber: 17\n      }, this)\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 58,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"Exceptions can be Categorized into 2 Ways:\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 69,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"ul\", {\n      children: [/*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Built-in Exceptions\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 71,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"ul\", {\n        children: [/*#__PURE__*/_jsxDEV(\"li\", {\n          children: \"Checked Exception\"\n        }, void 0, false, {\n          fileName: _jsxFileName,\n          lineNumber: 73,\n          columnNumber: 9\n        }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n          children: \"Unchecked Exception\"\n        }, void 0, false, {\n          fileName: _jsxFileName,\n          lineNumber: 74,\n          columnNumber: 9\n        }, this)]\n      }, void 0, true, {\n        fileName: _jsxFileName,\n        lineNumber: 72,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"User-Defined Exceptions\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 76,\n        columnNumber: 5\n      }, this)]\n    }, void 0, true, {\n      fileName: _jsxFileName,\n      lineNumber: 70,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"1. Built-in Exceptions:\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 79,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n      children: \"Built-in exceptions are the exceptions that are available in Java libraries. These exceptions are suitable to explain certain error situations.\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 80,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"ul\", {\n      children: [/*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Checked Exceptions:\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 82,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n        children: \"Checked exceptions are called compile-time exceptions because these exceptions are checked at compile-time by the compiler.\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 83,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Unchecked Exceptions:\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 84,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n        children: \"The unchecked exceptions are just opposite to the checked exceptions. The compiler will not check these exceptions at compile time. In simple words, if a program throws an unchecked exception, and even if we didn\\u2019t handle or declare it, the program would not give a compilation error.\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 85,\n        columnNumber: 5\n      }, this)]\n    }, void 0, true, {\n      fileName: _jsxFileName,\n      lineNumber: 81,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"h3\", {\n      children: \"2. User-Defined Exceptions:\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 88,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n      children: \"Sometimes, the built-in exceptions in Java are not able to describe a certain situation. In such cases, users can also create exceptions which are called \\u2018user-defined Exceptions\\u2019. \"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 89,\n      columnNumber: 2\n    }, this), /*#__PURE__*/_jsxDEV(\"p\", {\n      children: \"The advantages of Exception Handling in Java are as follows:\"\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 91,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"ul\", {\n      children: [/*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Provision to Complete Program Execution\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 93,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Easy Identification of Program Code and Error-Handling Code\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 94,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Propagation of Errors\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 95,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Meaningful Error Reporting\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 96,\n        columnNumber: 5\n      }, this), /*#__PURE__*/_jsxDEV(\"li\", {\n        children: \"Identifying Error Types\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 97,\n        columnNumber: 5\n      }, this)]\n    }, void 0, true, {\n      fileName: _jsxFileName,\n      lineNumber: 92,\n      columnNumber: 1\n    }, this), /*#__PURE__*/_jsxDEV(\"div\", {\n      className: \"player\",\n      controls: true,\n      children: /*#__PURE__*/_jsxDEV(ReactPlayer, {\n        url: \"https://www.youtube.com/watch?v=cjNVLIBXoes\"\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 106,\n        columnNumber: 3\n      }, this)\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 105,\n      columnNumber: 1\n    }, this)]\n  }, void 0, true, {\n    fileName: _jsxFileName,\n    lineNumber: 10,\n    columnNumber: 5\n  }, this);\n};\n\n_c = Exceptionhandling;\nexport default Exceptionhandling;\n\nvar _c;\n\n$RefreshReg$(_c, \"Exceptionhandling\");","map":{"version":3,"sources":["C:/E-Lfront/PGDAC-Final-E-Learning-Frontend/my-app/src/Pages/ChapterContent/Exceptionhandling.js"],"names":["React","Carousel","ReactPlayer","ContentNavi","Exceptionhandling","require"],"mappings":";AAAA,OAAOA,KAAP,MAAkB,OAAlB;AACA,OAAOC,QAAP,MAAqB,0BAArB;AACA,OAAOC,WAAP,MAAwB,cAAxB;AACA,OAAO,aAAP;AACA,OAAOC,WAAP,MAAwB,qCAAxB;;;AAEA,MAAMC,iBAAiB,GAAG,MAAM;AAC9B,sBAEE;AAAK,IAAA,SAAS,EAAC,SAAf;AAAA,4BACI,QAAC,WAAD;AAAA;AAAA;AAAA;AAAA,YADJ,eAEI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YAFJ,eAII;AAAA;AAAA;AAAA;AAAA,YAJJ,oBAIU;AAAA;AAAA;AAAA;AAAA,YAJV,eAKI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YALJ,eAOJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YAPI,eAQJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YARI,eAWJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YAXI,eAYJ;AAAA,8BACI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cADJ,eAEI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAFJ,eAGI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAHJ,eAII;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAJJ,eAKI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cALJ,eAMI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cANJ;AAAA;AAAA;AAAA;AAAA;AAAA,YAZI,eAqBJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YArBI,eAsBJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YAtBI,eA0BJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YA1BI,eA2BJ;AAAA,8BACI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cADJ,eAEI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAFJ;AAAA;AAAA;AAAA;AAAA;AAAA,YA3BI,eAiCJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YAjCI,eAkCJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YAlCI,eAmCJ,QAAC,QAAD;AAAA,6BACgB,QAAC,QAAD,CAAU,IAAV;AAAe,QAAA,QAAQ,EAAE,IAAzB;AAAA,gCACA,QAAC,QAAD,CAAU,OAAV;AAAA;AAAA;AAAA;AAAA,gBADA,eAKI;AAAK,UAAA,GAAG,EAAEC,OAAO,CAAC,2EAAD,CAAjB;AAAgG,UAAA,SAAS,EAAC;AAA1G;AAAA;AAAA;AAAA;AAAA,gBALJ;AAAA;AAAA;AAAA;AAAA;AAAA;AADhB;AAAA;AAAA;AAAA;AAAA,YAnCI,eA8CJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YA9CI,eA+CJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YA/CI,eAgDJ,QAAC,QAAD;AAAA,6BACgB,QAAC,QAAD,CAAU,IAAV;AAAe,QAAA,QAAQ,EAAE,IAAzB;AAAA,gCACA,QAAC,QAAD,CAAU,OAAV;AAAA;AAAA;AAAA;AAAA,gBADA,eAKI;AAAK,UAAA,GAAG,EAAEA,OAAO,CAAC,uFAAD,CAAjB;AAA4G,UAAA,SAAS,EAAC;AAAtH;AAAA;AAAA;AAAA;AAAA,gBALJ;AAAA;AAAA;AAAA;AAAA;AAAA;AADhB;AAAA;AAAA;AAAA;AAAA,YAhDI,eA2DJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YA3DI,eA4DJ;AAAA,8BACI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cADJ,eAEI;AAAA,gCACI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,gBADJ,eAEI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,gBAFJ;AAAA;AAAA;AAAA;AAAA;AAAA,cAFJ,eAMI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cANJ;AAAA;AAAA;AAAA;AAAA;AAAA,YA5DI,eAqEJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YArEI,eAsEJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YAtEI,eAuEJ;AAAA,8BACI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cADJ,eAEI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAFJ,eAGI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAHJ,eAII;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAJJ;AAAA;AAAA;AAAA;AAAA;AAAA,YAvEI,eA8EJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YA9EI,eA+EH;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YA/EG,eAiFJ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,YAjFI,eAkFJ;AAAA,8BACI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cADJ,eAEI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAFJ,eAGI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAHJ,eAII;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cAJJ,eAKI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,cALJ;AAAA;AAAA;AAAA;AAAA;AAAA,YAlFI,eA+FJ;AAAK,MAAA,SAAS,EAAC,QAAf;AAAwB,MAAA,QAAQ,MAAhC;AAAA,6BACE,QAAC,WAAD;AAAa,QAAA,GAAG,EAAC;AAAjB;AAAA;AAAA;AAAA;AAAA;AADF;AAAA;AAAA;AAAA;AAAA,YA/FI;AAAA;AAAA;AAAA;AAAA;AAAA,UAFF;AAyGD,CA1GD;;KAAMD,iB;AA6GN,eAAeA,iBAAf","sourcesContent":["import React from 'react'\r\nimport Carousel from 'react-bootstrap/Carousel';\r\nimport ReactPlayer from 'react-player';\r\nimport './index.css'\r\nimport ContentNavi from '../../Components/Navbar/ContentNavi';\r\n\r\nconst Exceptionhandling = () => {\r\n  return (\r\n\r\n    <div className='Content'>\r\n        <ContentNavi/>\r\n        <h1>Exceptions in Java</h1>\r\n\r\n        <br/> <br/>\r\n        <p>Exception Handling in Java is one of the effective means to handle the runtime errors so that the regular flow of the application can be preserved. Java Exception Handling is a mechanism to handle runtime errors such as ClassNotFoundException, IOException, SQLException, RemoteException, etc.</p>\r\n\r\n<h3>What is an Exception?</h3>\r\n<p>An exception is an unwanted or unexpected event, which occurs during the execution of a program i.e at run time, that disrupts the normal flow of the program’s instructions. Exceptions can be caught and handled by the program. When an exception occurs within a method, it creates an object. This object is called the exception object. It contains information about the exception such as the name and description of the exception and the state of the program when the exception occurred.</p>\r\n\r\n\r\n<h3>An exception can occur for many reasons. Some of them are:</h3>\r\n<ul>\r\n    <li>Invalid user input</li>\r\n    <li>Device failure</li>\r\n    <li>Loss of network connection</li>\r\n    <li>Physical limitations (out of disk memory)</li>\r\n    <li>Code errors</li>\r\n    <li>Opening an unavailable file</li>\r\n</ul>\r\n\r\n<h3>What is an Error? </h3>\r\n<p>Errors represent irrecoverable conditions such as Java virtual machine (JVM) running out of memory, memory leaks, stack overflow errors, library incompatibility, infinite recursion, etc.\r\n\r\nErrors are usually beyond the control of the programmer and we should not try to handle errors.</p>\r\n\r\n<h3>Error vs Exception</h3>\r\n<ul>\r\n    <li>Error: An Error indicates a serious problem that a reasonable application should not try to catch.</li>\r\n    <li>Exception: Exception indicates conditions that a reasonable application might try to catch.</li>\r\n</ul>\r\n\r\n\r\n<h3>Exception Hierarchy</h3>\r\n<p>All exception and errors types are subclasses of class Throwable, which is the base class of the hierarchy. One branch is headed by Exception. This class is used for exceptional conditions that user programs should catch. NullPointerException is an example of such an exception. Another branch, Error is used by the Java run-time system(JVM) to indicate errors having to do with the run-time environment itself(JRE). StackOverflowError is an example of such an error.</p>\r\n<Carousel>\r\n                <Carousel.Item interval={1000}>\r\n                <Carousel.Caption>\r\n                   {/* // <h2 style={{ color: 'orange' }}>Your Car Our Responsibility...</h2> */}\r\n                    \r\n                </Carousel.Caption>\r\n                    <img src={require('https://media.geeksforgeeks.org/wp-content/uploads/Exception-in-java1.png')} className=\"img\"  ></img>\r\n                </Carousel.Item>    \r\n \r\n</Carousel>\r\n\r\n<h3>Types of Exceptions</h3> \r\n<p>Java defines several types of exceptions that relate to its various class libraries. Java also allows users to define their own exceptions.</p>\r\n<Carousel>\r\n                <Carousel.Item interval={1000}>\r\n                <Carousel.Caption>\r\n                   {/* // <h2 style={{ color: 'orange' }}>Your Car Our Responsibility...</h2> */}\r\n                    \r\n                </Carousel.Caption>\r\n                    <img src={require('https://media.geeksforgeeks.org/wp-content/uploads/20220120111809/Group21-660x330.jpg')} className=\"img\"  ></img>\r\n                </Carousel.Item>    \r\n \r\n</Carousel>\r\n\r\n<h3>Exceptions can be Categorized into 2 Ways:</h3>\r\n<ul>\r\n    <li>Built-in Exceptions</li>\r\n    <ul>\r\n        <li>Checked Exception</li>\r\n        <li>Unchecked Exception</li>\r\n    </ul>\r\n    <li>User-Defined Exceptions</li>\r\n</ul>\r\n\r\n<h3>1. Built-in Exceptions:</h3> \r\n<p>Built-in exceptions are the exceptions that are available in Java libraries. These exceptions are suitable to explain certain error situations.</p>\r\n<ul>\r\n    <li>Checked Exceptions:</li>\r\n    <p>Checked exceptions are called compile-time exceptions because these exceptions are checked at compile-time by the compiler.</p>\r\n    <li>Unchecked Exceptions:</li>\r\n    <p>The unchecked exceptions are just opposite to the checked exceptions. The compiler will not check these exceptions at compile time. In simple words, if a program throws an unchecked exception, and even if we didn’t handle or declare it, the program would not give a compilation error.</p>\r\n</ul>\r\n\r\n<h3>2. User-Defined Exceptions:</h3>\r\n <p>Sometimes, the built-in exceptions in Java are not able to describe a certain situation. In such cases, users can also create exceptions which are called ‘user-defined Exceptions’. </p>\r\n\r\n<p>The advantages of Exception Handling in Java are as follows:</p>\r\n<ul>\r\n    <li>Provision to Complete Program Execution</li>\r\n    <li>Easy Identification of Program Code and Error-Handling Code</li>\r\n    <li>Propagation of Errors</li>\r\n    <li>Meaningful Error Reporting</li>\r\n    <li>Identifying Error Types</li>\r\n</ul>\r\n\r\n\r\n\r\n\r\n\r\n\r\n<div className='player' controls>\r\n  <ReactPlayer url='https://www.youtube.com/watch?v=cjNVLIBXoes'/>\r\n</div>\r\n\r\n\r\n\r\n    </div>\r\n    )\r\n}\r\n    \r\n\r\nexport default Exceptionhandling"]},"metadata":{},"sourceType":"module"}